[package]
name = "rsudoku"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2.15", features = ["js"] }
js-sys = "0.3.70"
rand = "0.8.5"
wasm-bindgen = "0.2.93"
